import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { createPglitePool } from '../../src/adapters/pglite/index.js';
import { createPostgresAdapter } from '../../src/adapters/postgres/index.js';
import { createQueryEngine } from '../../src/engine/runtime.js';
import { executeMutation } from '../../src/mutations/engine.js';
import { handleQuery } from '../../src/handler.js';
import { createQueryTools } from '../../src/agent/tools.js';
import { VexError } from '../../src/errors.js';
import type { Query } from '../../src/schemas/query.schema.js';
import type { DatabaseSchema } from '../../src/schemas/database.schema.js';
import type { ScopePolicy } from '../../src/scope/scope.types.js';
import type { GenerateDsl, GenerationCaller } from '../../src/types.js';

// WHO IS ASKING, and what happens when nobody says.
//
// A policy is enforced whenever an engine has one. The caller's scope values
// fill the row rules' `$scope` slots and do nothing else — so an engine with no
// policy, or a policy with no row rules, needs no values at all, and a policy
// WITH row rules refuses a statement nobody scoped instead of reading it as
// everybody. That last case used to switch the whole policy off, table access
// included.
//
// The second half is generation: the agent that writes a query reaches the
// database only through a `read` capability run as its caller, and is shown only
// the tables that caller may read.

const DDL = `
  CREATE TABLE notes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, body TEXT, due DATE);
  CREATE TABLE secrets (id TEXT PRIMARY KEY, secret TEXT NOT NULL);
  INSERT INTO notes VALUES
    ('n1', 'acme', 'hello', '2026-01-01'),
    ('n2', 'bolt', 'other', '2026-02-01'),
    ('n3', 'acme', NULL, '2026-03-01');
  INSERT INTO secrets VALUES ('s1', 'hunter2');
`;

const tableOnly: ScopePolicy = { default: 'deny', entities: { notes: { public: true } } };
const byTenant: ScopePolicy = {
  default: 'deny',
  entities: {
    notes: {
      read: [{ match: 'tenant_id', to: 'tenantId' }],
      write: [{ set: 'tenant_id', to: 'tenantId' }, { match: 'tenant_id', to: 'tenantId' }],
    },
  },
};

const db = new PGlite();
const pool = createPglitePool(db);
const adapter = createPostgresAdapter({ pool });
let schema: DatabaseSchema;

const allNotes: Query = { from: ['notes'], fields: ['notes.id'], sort: [{ field: 'notes.id', dir: 'asc' }] };
const ids = (result: unknown): unknown[] => (Array.isArray(result) ? result.map((r: Record<string, unknown>) => r['id']) : []);

// An engine whose only query is generated by `hook` — so a test can run a
// DSL of its choosing through the whole execute path, generation included.
const engineWith = async (policy: ScopePolicy | undefined, hook: GenerateDsl) => {
  const engine = createQueryEngine({ adapter, ...(policy !== undefined ? { scope: policy } : {}), generateDsl: hook });
  await engine.introspect();
  return engine;
};
const returning = (dsl: Query): GenerateDsl => async () => dsl;
const ask = { intent: 'the notes', shape: [{ id: '' }], context: {} };

beforeAll(async () => {
  await db.exec(DDL);
  const probe = createQueryEngine({ adapter });
  schema = await probe.introspect();
});

afterAll(async () => {
  await db.close();
});

describe('an engine with no policy is open, and needs nobody', () => {
  it('reads every row with no scope values', async () => {
    const engine = await engineWith(undefined, returning(allNotes));
    expect(ids((await engine.execute(ask)).result)).toEqual(['n1', 'n2', 'n3']);
  });
});

describe('a policy with no row rules needs no values — and is enforced without them', () => {
  it('reads the table it allows', async () => {
    const engine = await engineWith(tableOnly, returning(allNotes));
    expect(ids((await engine.execute(ask)).result)).toEqual(['n1', 'n2', 'n3']);
  });

  it('refuses the table it denies, though nobody passed a value (this used to read it)', async () => {
    const engine = await engineWith(tableOnly, returning({ from: ['secrets'], fields: ['secrets.secret'] }));
    await expect(engine.execute(ask)).rejects.toMatchObject({ code: 'scope_denied' });
  });
});

describe('a policy with row rules refuses a statement nobody scoped', () => {
  it('reads only the caller tenant when the host says who it is', async () => {
    const engine = await engineWith(byTenant, returning(allNotes));
    expect(ids((await engine.execute(ask, { scope: { tenantId: 'acme' } })).result)).toEqual(['n1', 'n3']);
  });

  it('refuses when the values are omitted (this used to read every tenant)', async () => {
    const engine = await engineWith(byTenant, returning(allNotes));
    await expect(engine.execute(ask)).rejects.toMatchObject({ code: 'missing_scope' });
  });

  it('refuses when the values are there but the one the rule needs is not', async () => {
    const engine = await engineWith(byTenant, returning(allNotes));
    await expect(engine.execute(ask, { scope: { userId: 'u1' } })).rejects.toMatchObject({ code: 'missing_scope' });
  });

  it('over HTTP it is the server’s fault, and the key names stay on the server', async () => {
    const engine = await engineWith(byTenant, returning(allNotes));
    const outcome = await handleQuery({ engine }, ask, {});
    expect(outcome.status).toBe(500);
    expect(JSON.stringify(outcome.body)).not.toContain('tenantId');
  });

  it('a missing CONTEXT value is still the caller’s, and answers empty with the contract', async () => {
    const engine = await engineWith(byTenant, returning({ ...allNotes, filter: { eq: ['notes.body', { $context: 'body' }] } }));
    const response = await engine.execute(ask, { scope: { tenantId: 'acme' } });
    expect(response.result).toEqual([]);
    expect(response.meta.missingContext).toEqual(['body']);
  });

  it('engine.test runs as somebody or is refused', async () => {
    const engine = await engineWith(byTenant, returning(allNotes));
    expect((await engine.test(allNotes)).errors.join()).toContain('did not supply');
    expect((await engine.test(allNotes, { tenantId: 'acme' })).rows.map((r) => r['id']).sort()).toEqual(['n1', 'n3']);
  });
});

describe('a write nobody scoped writes nothing', () => {
  it('an insert whose owner the host did not supply is refused, not stamped NULL', async () => {
    const insert = { op: 'insert' as const, table: 'notes', values: { id: 'n9', body: 'orphan' } };
    await expect(executeMutation(pool, insert, { context: {}, scope: {}, policy: byTenant, schema })).rejects.toMatchObject({ code: 'missing_scope' });
    const rows = await pool.query(`SELECT id FROM notes WHERE id = 'n9'`);
    expect(rows.rows).toEqual([]);
  });
});

describe('a generating agent reads as its caller', () => {
  // A hook that records what it was handed and probes through its capability.
  const spy = () => {
    const seen: { schema?: DatabaseSchema; caller?: GenerationCaller } = {};
    const hook: GenerateDsl = async (_request, handed, caller) => {
      seen.schema = handed;
      seen.caller = caller;
      return allNotes;
    };
    return { seen, hook };
  };

  it('is shown only the tables its caller may read', async () => {
    const { seen, hook } = spy();
    const engine = await engineWith(byTenant, hook);
    await engine.execute(ask, { scope: { tenantId: 'acme' } });
    expect(seen.schema?.entities.map((e) => e.name)).toEqual(['notes']);
  });

  it('reads the caller’s rows through its capability, and nobody else’s', async () => {
    const { seen, hook } = spy();
    const engine = await engineWith(byTenant, hook);
    await engine.execute(ask, { scope: { tenantId: 'bolt' } });
    const probe = await seen.caller?.read(allNotes);
    expect(probe?.rows.map((r) => r['id'])).toEqual(['n2']);
  });

  it('cannot read a table its caller may not, even by asking for it directly', async () => {
    const { seen, hook } = spy();
    const engine = await engineWith(byTenant, hook);
    await engine.execute(ask, { scope: { tenantId: 'acme' } });
    await expect(seen.caller?.read({ from: ['secrets'], fields: ['secrets.secret'] })).rejects.toBeInstanceOf(VexError);
  });

  it('binds $context as NULL, never a typed guess, and scope as the caller’s own', async () => {
    const { seen, hook } = spy();
    const engine = await engineWith(byTenant, hook);
    await engine.execute(ask, { scope: { tenantId: 'acme' } });
    // A date compared against NULL is valid SQL; an empty-string guess would be
    // a cast error, which once taught the agent the DSL "cannot" compare dates.
    const probe = await seen.caller?.read({ ...allNotes, filter: { gt: ['notes.due', { $context: 'after' }] } });
    expect(probe?.rows).toEqual([]);
    expect(probe?.sql).toContain('tenant_id');
  });

  it('one caller’s "cannot satisfy" is not another’s', async () => {
    let calls = 0;
    const hook: GenerateDsl = async () => {
      calls += 1;
      throw new VexError('unsatisfiable', 'no such table for you');
    };
    const engine = createQueryEngine({ adapter, generateDsl: hook });
    await engine.introspect();
    await expect(engine.execute(ask, { scopePolicy: byTenant, scope: { tenantId: 'acme' } })).rejects.toMatchObject({ code: 'unsatisfiable' });
    await expect(engine.execute(ask, { scopePolicy: tableOnly })).rejects.toMatchObject({ code: 'unsatisfiable' });
    // Two policies, two generations — the second was not served the first's refusal.
    expect(calls).toBe(2);
    // The same policy again IS served from the negative cache.
    await expect(engine.execute(ask, { scopePolicy: tableOnly })).rejects.toMatchObject({ code: 'unsatisfiable' });
    expect(calls).toBe(2);
  });
});

describe('the query tools have no door but the caller’s', () => {
  const context = { runId: 'r', agentId: 'a', agentPath: ['a'], signal: new AbortController().signal, forward: () => () => undefined };

  const toolsFor = async (tenantId: string) => {
    const { seen, hook } = (() => {
      const box: { caller?: GenerationCaller; schema?: DatabaseSchema } = {};
      const h: GenerateDsl = async (_r, s, c) => {
        box.caller = c;
        box.schema = s;
        return allNotes;
      };
      return { seen: box, hook: h };
    })();
    const engine = await engineWith(byTenant, hook);
    await engine.execute(ask, { scope: { tenantId } });
    const { caller, schema: handed } = seen;
    if (caller === undefined || handed === undefined) throw new Error('the hook was never called');
    const tools = createQueryTools({ getSchema: () => handed, read: caller.read });
    const tool = (id: string) => {
      const found = tools.find((t) => t.config.id === id);
      if (found === undefined) throw new Error(`no tool ${id}`);
      return (input: unknown) => found.config.execute(input, context);
    };
    return tool;
  };

  it('samples only the caller’s rows', async () => {
    const tool = await toolsFor('acme');
    const rows = await tool('getSampleRows')({ entity: 'notes' });
    expect(Array.isArray(rows) ? rows.map((r: Record<string, unknown>) => r['tenant_id']) : rows).toEqual(['acme', 'acme']);
  });

  it('counts distinct values among the caller’s rows only', async () => {
    const tool = await toolsFor('bolt');
    expect(await tool('getDistinctValues')({ entity: 'notes', field: 'body' })).toEqual(['other']);
    expect(await tool('describeField')({ entity: 'notes', field: 'body' })).toMatchObject({ cardinality: 1, nullCount: 0 });
  });

  it('describes a field from the caller’s rows — nulls and range included', async () => {
    const tool = await toolsFor('acme');
    expect(await tool('describeField')({ entity: 'notes', field: 'body' })).toMatchObject({ cardinality: 1, nullCount: 1 });
    const due = await tool('describeField')({ entity: 'notes', field: 'due' });
    expect(due).toMatchObject({ cardinality: 2, nullCount: 0 });
  });

  it('a table the caller cannot read is not there to sample', async () => {
    const tool = await toolsFor('acme');
    expect(await tool('getSampleRows')({ entity: 'secrets' })).toMatchObject({ error: 'Entity "secrets" not found' });
  });

  it('testQuery runs as the caller', async () => {
    const tool = await toolsFor('bolt');
    const result = await tool('testQuery')(allNotes);
    expect(result).toMatchObject({ errors: [], rows: [{ id: 'n2' }] });
  });
});
