import type { SeedEntry, SeedMutation } from '@niscorp/vex';
import { studioCurrent, studioTheme, membersActiveCount, checkInsTodayCount, studioSetReplyTo, studioSetDomain, outboxSentToday } from './studio.entries';
import { revenueAtRisk, revenueCommitted, revenueExpected, revenueLeaving } from './forecast.entries';
import { sessionsToday, sessionsUpcoming, programsList } from './schedule.entries';
import { sessionAttending, sessionDetail } from './session.entries';
import { peopleList, peopleCount, personById, offeringsList, offeringOptions, offeringsOnSale } from './member.entries';
import { personAnchorUpdate, personConsentSet } from './member.mutations';
import { subscriptionAssert, subscriptionBillable, subscriptionForMember, subscriptionGiveNotice, subscriptionWithdrawNotice, subscriptionStart, subscriptionRecordPayment, subscriptionEnd, subscriptionPause, subscriptionResume, myMembership, passSell, passesForPerson, enrolPerson, offeringPrice, coursePrice, offeringsPurchasable, purchaseRecord, purchasesForPerson } from './subscription.entries';
import { localeCurrent, studioSetLocale, studioSetTheme, themeCurrent, themesList } from './theme.entries';
import { bookableForSession, bookingCancel, bookingCreate, checkInMark, rosterForSession, walkInsToday } from './desk.entries';
import {
  programCreate,
  programUpdate,
  sessionCancel,
  sessionRestore,
  teachersList,
  templateById,
  templateCreate,
  templatesCreateEach,
  templateSetActive,
  templateUpdate,
  templatesList,
  eventCreate,
} from './timetable.entries';
import { staffById, staffCreate, staffEnroll, staffList, staffSetActive, staffSetRole } from './staff.entries';
import { bookClass, cancelMyBooking, myBookedSessions, myBookings, myCard, myPasses } from './me.entries';
import { enquiredPerson, membersLapsedAway, automationArm, automationCreate, automationUpdate, automationsList, automationRecipes, automationRuns, bookingsOnDay, joinedSubscription, followUpsOpen, notificationsUnseen, notificationsMarkSeen, outboxRecent, outboxQueued, outboxStuck, outboxClaim, outboxSent, outboxFailed, outboxRequeue, closeFollowUp, notify, queueMessage, trialsDue } from './tide.entries';
import { courseCreate, courseSetActive, courseRoster, courseUpdate, coursesList, enrolMember, enrolmentsForMember, joinCourse, leaveCourse, myEnrolments, withdrawMember } from './course.entries';
import { studioPersonCreate, peopleEnroll, personByEmail, personCreate } from './intake.entries';
import { identityPerson, identityStudio, identityInstalled } from './identity.entries';
import { phrasesBook, phrasesLocales, phrasesIntegrations } from './language.entries';
import { credentialPrincipalByEmail, credentialSweepLinks, credentialMintLink, credentialRedeemLink, mailerRecordDelivered, mailerRecordFailed, mailerOutboxOrigin, mailerSuppress, mailerOptOut, transportStaffRoster, transportMemberRoster, schedulerReflexRows, schedulerStudioZones } from './machinery.entries';
import { addonInstall, addonUninstall, addonsInstalled, addonsList } from './addon.entries';
import { attendanceByHour, attendanceByProgram, attendanceByWeek, membersByStatus, offeringCreate, offeringSetActive, offeringUpdate, planUptake } from './reports.entries';

export type CacheEntry = SeedEntry;
export type MutationEntry = SeedMutation;

export const ENTRIES: CacheEntry[] = [
  studioCurrent,
  membersActiveCount,
  checkInsTodayCount,
  revenueExpected,
  revenueCommitted,
  revenueLeaving,
  revenueAtRisk,
  sessionsToday,
  sessionDetail,
  sessionAttending,
  sessionsUpcoming,
  programsList,
  addonsList,
  addonsInstalled,
  // The roll, lensed: the lens is a context value, not a fingerprint.
  peopleList,
  peopleCount,
  personById,
  offeringsList,
  offeringOptions,
  offeringsOnSale,
  themeCurrent,
  themesList,
  localeCurrent,
  rosterForSession,
  walkInsToday,
  bookableForSession,
  templatesList,
  templateById,
  teachersList,
  staffList,
  staffById,
  myCard,
  myPasses,
  myMembership,
  myBookings,
  myBookedSessions,
  coursesList,
  courseRoster,
  enrolmentsForMember,
  myEnrolments,
  passesForPerson,
  trialsDue,
  automationRuns,
  bookingsOnDay,
  followUpsOpen,
  notificationsUnseen,
  outboxRecent,
  outboxQueued,
  outboxStuck,
  outboxSentToday,
  automationsList,
  automationRecipes,
  joinedSubscription,
  enquiredPerson,
  membersLapsedAway,
  personByEmail,
  attendanceByHour,
  attendanceByWeek,
  attendanceByProgram,
  membersByStatus,
  planUptake,
  subscriptionForMember,
  subscriptionBillable,
  offeringsPurchasable,
  purchasesForPerson,
  offeringPrice,
  coursePrice,
  // The session's own facts, self-pinned at the identity reach. The licensed
  // pre-auth entries (identity/roles, identity/actor, and friends) are
  // DELIBERATELY not here: a pre-auth read on the wire is the hole D4 refused,
  // and reads-are-vex-check asserts their absence.
  identityPerson,
  identityStudio,
  identityInstalled,
  studioTheme,
  phrasesBook,
  phrasesLocales,
  phrasesIntegrations,
  credentialPrincipalByEmail,
  mailerOutboxOrigin,
  transportStaffRoster,
  transportMemberRoster,
  schedulerReflexRows,
  schedulerStudioZones,
];

// Every write the app can make. Replay-only forever: never generated, linted at
// seed, and the statement lives server-side where a request cannot see it.
export const MUTATION_ENTRIES: MutationEntry[] = [
  // the no-principal machinery, executed only via `server.executeAs`
  credentialSweepLinks,
  credentialMintLink,
  credentialRedeemLink,
  mailerRecordDelivered,
  mailerRecordFailed,
  mailerSuppress,
  mailerOptOut,
  addonInstall,
  addonUninstall,
  personAnchorUpdate,
  personConsentSet,
  subscriptionStart,
  subscriptionRecordPayment,
  subscriptionEnd,
  passSell,
  enrolPerson,
  purchaseRecord,
  subscriptionGiveNotice,
  subscriptionPause,
  subscriptionResume,
  subscriptionWithdrawNotice,
  subscriptionAssert,
  studioSetTheme,
  studioSetLocale,
  studioSetReplyTo,
  studioSetDomain,
  checkInMark,
  bookingCreate,
  bookingCancel,
  templateCreate,
  templatesCreateEach,
  templateUpdate,
  templateSetActive,
  sessionCancel,
  sessionRestore,
  programCreate,
  programUpdate,
  bookClass,
  cancelMyBooking,
  notify,
  closeFollowUp,
  notificationsMarkSeen,
  queueMessage,
  outboxClaim,
  outboxSent,
  outboxFailed,
  outboxRequeue,
  automationCreate,
  automationUpdate,
  automationArm,
  courseCreate,
  courseUpdate,
  courseSetActive,
  joinCourse,
  leaveCourse,
  eventCreate,
  enrolMember,
  withdrawMember,
  staffCreate,
  staffEnroll,
  staffSetRole,
  staffSetActive,
  personCreate,
  studioPersonCreate,
  peopleEnroll,
  offeringCreate,
  offeringUpdate,
  offeringSetActive,
];
