// THE DECK — data, and nothing else: the slides in order, each with the tools
// the controller shows beside it and the speaker's notes. db/seed.ts writes it
// to the database on every boot; the census counts this file as data
// (server/census.ts).
//
// In order. Each slide id is an action the stage is granted, each
// tool id one the speaker is granted — `deck-check` asserts both. The tools are
// what the controller shows while that slide is up, stacked in this order. The words are
// provisional: the talk's text is written with the story.
export const SLIDES: readonly { slideId: string; title: string; tools: readonly string[]; notes: readonly string[] }[] = [
  // ── the opening: where it started, the problem, our answer, and Nova ──
  { slideId: 'slide.title', title: 'nisc', tools: [], notes: ['[join: scan the code or type the address]', 'this talk is an app, running now, on one server', 'stage + my controller + your phones = one app', 'laptops: open the address, devtools open', 'terminal: the SSH command works too', 'join: pick a name or type one'] },
  { slideId: 'stage.register', title: 'Everyone who has joined', tools: [], notes: ['each name = a row in the database', 'names you typed: a model checked them first', '[wait until most people are in]'] },
  { slideId: 'slide.timer', title: 'First, a timer.', tools: ['assistant.thread'], notes: ['[share the controller screen]', '[type: "Show the last slide in 30 minutes"]', 'the answer is a document: when it fires, what it does', '[read it out, press Save, stop sharing]', 'back to this at the end'] },
  { slideId: 'slide.origin', title: 'GPT-3 could not write a React app.', tools: [], notes: ['2020, GPT-3', 'wanted it to build UI → no working React app', 'it could fill in a JSON schema, mostly', 'JSON can be checked before it runs', '→ what if the UI is JSON?'] },
  { slideId: 'slide.problem', title: 'Models write code faster than anyone can review it.', tools: [], notes: ['models write more code than anyone can review', 'every change still needs a person'] },
  { slideId: 'slide.answer', title: 'A program checks it. Not a person.', tools: [], notes: ['every part of the app = a JSON document + a schema', 'model writes it → program checks it → runtime runs it', 'code only in: renderers, endpoints, setup, tests', 'starts with the UI'] },
  { slideId: 'slide.nova', title: 'Nova', tools: [], notes: ['Nova = the UI part', 'a screen = a set of actions', 'action = JSON: its data, where data comes from, what a tap does, its layout', 'model writes it, schema checks it, Nova runs it', 'Nova doesn’t draw — a renderer does (slide 10)'] },
  { slideId: 'slide.data', title: 'An action', tools: [], notes: ['data: the draft, and whether it was sent', 'right: drawn here from the same JSON', 'tap Send → trigger on "send_btn" → steps → endpoint "post_question"', 'no fetch, no handler code', 'not on your phone — Acme’s comes later'] },
  { slideId: 'slide.xray', title: 'Your screen, as JSON.', tools: ['tools.xray'], notes: ['[give everyone the X-ray]', 'switch it on', 'every action outlined, with its id', 'tap an id → that action’s JSON', 'no code in it: a person, a program or a model can read it', '[take it back]'] },
  { slideId: 'slide.looks', title: 'One screen, any renderer.', tools: ['tools.look'], notes: ['so far: one small DOM renderer', '[phones → React] same JSON, same CSS; its column lights up', 'laptops: inspect the root element', '[stage → Vue] two frameworks at once', 'on the server: one row changed', '[all back to DOM]'] },
  { slideId: 'slide.terminal', title: 'SSH into it.', tools: ['tools.renderers'], notes: ['[type the command on screen]', 'you join like on your phone', 'Nova renders into a terminal too: a kit for ink', 'same JSON, drawn as text'] },
  { slideId: 'slide.compare', title: 'Isn’t this json-render?', tools: [], notes: ['json-render (Vercel), A2UI (Google): same direction', 'model writes JSON, a renderer draws it', '2 differences → why the demos just worked'] },
  { slideId: 'slide.parts', title: 'json-render ≈ Nova ∈ nisc', tools: [], notes: ['json-render: the screen as JSON — about what Nova does', 'more renderers than us; shadcn kit as an option', 'past the screen: Next.js and your code', 'nisc: the rest — server, authorization, queries, migrations, LLM — each its own package', 'A2UI: a protocol for an agent to send UI — a different job', 'next: how much of this app that is'] },
  { slideId: 'slide.census', title: 'Is JSON enough for a real app?', tools: [], notes: ['objection: JSON is fine for demos, not real apps', 'this app: slides, stage, controller, phones, SSH, assistant, timers', 'green: JSON data · blue: the code an app ships', 'one renderer, endpoints, setup', 'hatched: not the app — 4 extra kits for the demos, and tests', 'counted live from the source, comments excluded'] },

  // ── what a closed grammar buys: checks, at runtime and at build time ──
  { slideId: 'slide.checked', title: 'A closed grammar can be checked.', tools: [], notes: ['closed grammar → a program can check it, two ways', 'left: schema validation — a value that isn’t allowed', 'right: a check that reads behaviour — listens for x, sends x → a loop', 'a linter guesses about code; this is exact', 'more checks: calls only queries that exist, shows up only where allowed'] },
  { slideId: 'slide.runtime', title: 'Generated at runtime.', tools: [], notes: ['so a model can write these while the app runs', 'it writes → it’s validated → not valid? the errors go back → it writes again', 'usually fixed on the second run, rarely a third', 'you saw it: the timer · coming: your queries', 'validated = safe to run — is it the right thing? next'] },
  { slideId: 'slide.review', title: 'Review the result, not the code.', tools: [], notes: ['slide 5: models write code faster than anyone can review it', 'agent writes code → nobody reads all of it → slop', 'agent writes nisc → validation, then mechanical checks', 'what’s left: test the result → QA', 'QA: a person, or a model with vision', 'Lowdefy: same problem — config small enough for a person to read'] },
  { slideId: 'slide.install', title: 'Installing Acme’s Q&A', tools: ['tools.integrations'], notes: ['what this lets us do, safely: load somebody else’s UI and behaviour', 'Acme: the Q&A for this talk — a JSON file on GitHub, not part of this app', '[Install the broken one] → ✕ loop: it sends what it listens for', '[Install Acme] → four ✓', '[Approve] → on your phones + my controller', 'nobody read Acme’s file'] },

  // ── the rest of nisc, and the end ──
  { slideId: 'slide.moss', title: 'Your screen runs on the server.', tools: [], notes: ['how did I change your screens? X-ray, React, Acme', 'Moss: the app server — your screen runs on it', '[type half a question into Acme, don’t send, reload]', 'still there: your screen isn’t in your browser', 'laptops: second tab, same address → same screen'] },
  { slideId: 'slide.wire', title: 'Your phone only draws.', tools: [], notes: ['down: what to draw · up: what you pressed', 'that’s all that crosses', 'so any renderer works — you saw four', 'laptops: the websocket frames'] },
  { slideId: 'slide.manifest', title: 'The server is a list.', tools: [], notes: ['why Moss: nisc was all data, with no server to run it', 'every app rebuilt the same wiring', 'this is the whole server for this app: a list of its JSON', 'charter, actions, queries, row rules', 'json-render stops at the screen: then Next.js + your code'] },
  { slideId: 'slide.exists', title: 'It sends you only what you have.', tools: [], notes: ['usual server: one app for everyone, permission checks around it', 'Moss: each person is sent their own app', 'a kiosk with two actions is a two-action app', 'nothing to hide, nothing to forget to check', 'next: watch it'] },
  { slideId: 'slide.button', title: 'Some of you have an action now.', tools: ['tools.button'], notes: ['[give it to three people]', 'three of you have a button — hands up', 'volume up, press it → your name is up here', 'everyone else: look — it’s there or it isn’t', 'laptops: it’s not in your websocket frames', '[take it back]'] },
  { slideId: 'slide.where', title: 'Where do you check permissions?', tools: [], notes: ['how was that decided?', 'usually: three places', 'routes — an address, not what it does', 'components — hiding a button isn’t security', 'rows — can’t say "may not start a refund"', 'three rule sets that drift apart'] },
  { slideId: 'slide.charter', title: 'Who gets what: one file.', tools: [], notes: ['charter: role → which actions, which data, by pattern', 'member = all of you', 'button = the three: the action, and the one write it makes', 'who has a role = a row — no deploy', 'contradicts itself → the server refuses to start'] },
  { slideId: 'slide.twice', title: 'Enforced twice.', tools: [], notes: ['the charter enforces nothing itself → compiled into 2 checks', '1 · your screen: only what you’re given', '2 · every query: only your rows', 'your phone lists your questions — my controller lists everyone’s', 'same query, different rows', 'no field for someone else’s id'] },
  { slideId: 'slide.agents', title: 'The same file governs the AI.', tools: [], notes: ['your assistant can open only what you were given', 'the timer runs as clock: it can move the slide, nothing else', 'whatever a model wrote into it', 'one file: people and models'] },
  { slideId: 'slide.vex', title: 'Queries are JSON too.', tools: [], notes: ['Vex: this is the joined count at the top of the screen', 'stored: what it’s for, the shape of the answer, the query', 'the screen sends only its name — no SQL', 'reactive: someone joins → it answers again, everywhere', 'your permissions: applied inside the engine, every run', 'reshaping the rows = Prism, stored with it'] },
  { slideId: 'slide.words', title: 'Asked in words.', tools: ['tools.assistant', 'assistant.thread'], notes: ['[give everybody the assistant] → [ask it: how many people joined?]', 'small model picks: asked before? which shape?', 'asked before → the stored query runs, no model', 'new → a bigger model writes it, under your permissions, stored', 'not allowed → refused, with why', 'a model writes each query once; after that, no model'] },
  { slideId: 'slide.water', title: '18,000 cups of water.', tools: [], notes: ['2025: someone ordered 18,000 waters from Taco Bell’s drive-through AI', 'it stalled, staff stepped in; Taco Bell slowed the rollout', '2024: McDonald’s ended its IBM AI test — 260 McNuggets on one order', 'the AI acted on the order, no check in between'] },
  { slideId: 'slide.press', title: 'It can’t press Send.', tools: ['tools.order'], notes: ['assistant reads your screen — JSON, like the X-ray', 'it opens a form, filled in', 'it can’t press anything', '[give everyone the order form]', 'ask it for 18,000 cups of water → form opens, filled in', 'you don’t press Send'] },
  { slideId: 'slide.tide', title: 'The timer is a row.', tools: [], notes: ['back to the timer from slide 3', 'the row as stored: when, what it does, who it runs as', 'runs as clock — Save stamped that, not the model', 'no model running now', 'in the database → survives a restart'] },
  { slideId: 'slide.once', title: 'No agent loop.', tools: [], notes: ['other way: an agent with a skill (OpenClaw)', 'every run: a model reads the instructions, decides', 'tokens every run, different every run', 'here: a model wrote it once, I read it, saved it', 'runs with no model, same every time'] },
  { slideId: 'slide.strata', title: 'Grammars get migrations.', tools: [], notes: ['everything is a document → what happens when nisc changes?', 'tables have migrations → grammars too', 'grammar change without a migration → the check refuses it', 'stored documents carry their version → upgraded when read', 'newer than the reader → refused', 'this file: which versions this app is written in'] },
  { slideId: 'slide.end', title: 'It’s all in one folder.', tools: [], notes: ['[if the timer put this up] that was the timer — ran as clock, no model', 'the whole app: one folder', 'open source — scan the code — not on npm yet', 'questions: in Acme, on your phone'] },
];
