// THE DEMO DATASET, IN THE ORDER IT HAS TO BE WRITTEN.
//
// One fragment per subject, mirroring db/schema/ file for file, and the array
// in buildSeedSql is the order. It is a stricter order than the schema's,
// because rows have to satisfy the foreign keys AND arrive in the sequence the
// triggers expect: sessions exist before anything books one, check-ins land
// before `attended` is computed from them, and the class happening TODAY is
// written after the check-ins so nobody has already attended it.
//
// Some of what is here is fixture data and some is generated by SQL from the
// rows above it — a term of sessions, a third of them booked, four fifths of
// those attended. Both kinds live in the fragment for the table they fill.
import { VOCABULARY_SQL } from './vocabulary';
import { THEMES_SQL } from './themes';
import { PHRASES_SQL } from './phrases';
import { LUMEN, NORTHROCK, STUDIOS_SQL } from './studios';
import { CONNECTIONS_SQL, GUARDIANSHIPS_SQL, PEOPLE_SQL, STAFF_SQL, STUDIO_PEOPLE_SQL } from './people';
import { OFFERINGS_SQL } from './offerings';
import { SUBSCRIPTIONS_SQL } from './subscriptions';
import { NOTICES_SQL } from './notices';
import { PASSES_SQL } from './passes';
import { COURSES_SQL, PROGRAMS_SQL } from './programs';
import { CANCELLATION_SQL, COURSE_TEMPLATES_SQL, SESSIONS_SQL, TEMPLATES_SQL, TODAY_CLASS_SQL } from './classes';
import { ATTENDANCE_SQL, BOOKINGS_SQL, CHECK_INS_SQL, MEMBER_DIARY_SQL, WALK_IN_SQL } from './bookings';
import { ENROLMENTS_SQL } from './enrolments';
import { AUTOMATIONS_SQL } from './automations';

export { LUMEN, NORTHROCK };

export const buildSeedSql = (): string =>
  [
    VOCABULARY_SQL, //        the moments and effects an automation is built from
    THEMES_SQL,
    PHRASES_SQL,
    STUDIOS_SQL,
    PEOPLE_SQL,
    STAFF_SQL,
    STUDIO_PEOPLE_SQL, //     the anchor: everyone each studio knows
    OFFERINGS_SQL,
    SUBSCRIPTIONS_SQL,
    PASSES_SQL,
    NOTICES_SQL, //           derives the leaving dates on the subscriptions above
    PROGRAMS_SQL,
    COURSES_SQL,
    TEMPLATES_SQL,
    COURSE_TEMPLATES_SQL,
    SESSIONS_SQL, //          generated: a term of them, from the templates
    CANCELLATION_SQL,
    BOOKINGS_SQL, //          generated: a third of the seats, minus the two who stopped
    CHECK_INS_SQL, //         generated: four fifths of the past ones turned up
    WALK_IN_SQL,
    TODAY_CLASS_SQL, //       after the check-ins, so it has none
    ATTENDANCE_SQL, //        the booking's mirror of the check-in
    MEMBER_DIARY_SQL,
    ENROLMENTS_SQL,
    AUTOMATIONS_SQL,
    CONNECTIONS_SQL,
    GUARDIANSHIPS_SQL, //     who may act for whom — a record, until a reach reads it
  ].join('\n');

export const CAST = {
  lumen: { studio: LUMEN, owner: 'maren@lumen.studio', desk: 'ines@lumen.studio', instructor: 'tobias@lumen.studio', member: 'ava.klein@example.com' },
  northrock: { studio: NORTHROCK, owner: 'dario@northrock.gym', manager: 'kaya@northrock.gym', member: 'omar.haddad@example.com' },
} as const;
