import { KIND_CACHING, type VexScenario } from './scenarios';

// Builds the teaching snippet shown in the chrome Source tab: how a
// caller would issue this exact request against a wired engine. The read
// snippets show the FINGERPRINT round-trip the runtime actually performs —
// generate once, mint, replay — because that is how Vex is used.
export const buildSource = (s: VexScenario): string => {
  const json = (v: unknown): string => JSON.stringify(v, null, 2).replace(/\n/g, '\n  ');
  const fp = `vex-demo/${s.id}`;

  if (s.mode === 'compile') {
    return [
      "import { createQueryEngine } from '@niscorp/vex';",
      '',
      '// The analyzer runs inside compile() — before any SQL exists.',
      '// This DSL is rejected, so compile() throws VexError(invalid_dsl).',
      `const dsl = ${json(s.dsl)};`,
      '',
      'engine.compile(dsl); // ✗ cartesian product: no join between entities',
    ].join('\n');
  }

  if (s.mode === 'mutate') {
    if (s.mutation === undefined) {
      // The raw-body refusal demo: the request IS the lesson.
      return [
        '// Writes are REPLAY-ONLY. A mutation definition is not a request',
        '// shape — the wire knows { fingerprint, context } and nothing else,',
        '// so an inline definition dies at parse: 400 invalid_request.',
        '',
        `const body = ${json(s.body)};`,
        '',
        'await handleQuery({ engine, mutations: { client: db, policy } }, body, scope);',
        "// → { status: 400, body: { error: 'invalid_request', ... } }",
      ].join('\n');
    }
    return [
      "import { handleQuery, lintMutation } from '@niscorp/vex';",
      '',
      '// SEED TIME (boot, server-side): the definition is linted and stored',
      '// as a `kind: mutation` cache entry. It is never generated by an LLM',
      '// and it NEVER travels — the fingerprint is the whole API surface.',
      `const def = ${json(s.mutation)};`,
      `await engine.cache.set(${JSON.stringify(fp)}, { kind: 'mutation', mutation: def, ... });`,
      '',
      '// WIRE TIME: one wire shape, reads and writes alike — the entry\'s',
      '// kind picks the pipeline. Scope comes from the session, never the body.',
      'const res = await handleQuery(',
      '  { engine, mutations: { client: db, policy } },',
      `  { fingerprint: ${JSON.stringify(fp)}, context: ${json(s.context ?? {})} },`,
      `  ${json(s.scope ?? {})},`,
      ');',
      '',
      '// res.body.result → the RETURNING row(s); a refusal is a real status:',
      '// 400 scope_denied / missing_context / invalid_request.',
    ].join('\n');
  }

  const hasScope = s.scopeKey !== undefined;
  const opts = hasScope ? `, {\n  scope: ${json(s.scope ?? {})},\n}` : '';
  const seed = [
    '// SEED TIME (boot, server-side): the DSL is generated ONCE and stored',
    '// under a name. This is how an app PUBLISHES a read — the fingerprint',
    '// is the whole wire contract; context is runtime data, not identity.',
    `await engine.cache.set(${JSON.stringify(fp)}, {`,
    "  kind: 'ok',",
    `  dsl: ${json(s.dsl)},`,
    `  intent: ${JSON.stringify(s.intent)},`,
    `  shape: ${json(s.shape)},`,
    '  // …prismIr, schemaFingerprint, createdAt',
    '});',
  ];

  // "Then lock it" — the production posture. Seed, lock the endpoint,
  // replay works, ad-hoc generation is refused.
  if (s.locked === true) {
    return [
      "import { handleQuery } from '@niscorp/vex';",
      '',
      ...seed,
      '',
      '// SERVE TIME: mount the endpoint LOCKED — replay-only.',
      '//   vex({ engine, locked: true, getScope, getPolicy })   // hono adapter',
      '',
      '// A seeded fingerprint replays — zero LLM, deterministic pipeline only:',
      `await handleQuery({ engine, locked: true }, { fingerprint: ${JSON.stringify(fp)}, context: ${json(s.context ?? {})} }, scope);`,
      "// → { status: 200, body: { result, meta } }",
      '',
      '// An ad-hoc request (no / unknown fingerprint) is REFUSED — the model',
      '// cannot generate SQL against your data:',
      "await handleQuery({ engine, locked: true }, { intent: '…', shape: [/* … */] }, scope);",
      "// → { status: 400, body: { error: 'locked' } }",
    ].join('\n');
  }

  // "The published endpoint" — seed once, then the wire carries only the
  // fingerprint. The whole caching category rides this pattern.
  if (s.kind === KIND_CACHING) {
    return [
      "import { createQueryEngine } from '@niscorp/vex';",
      '',
      ...seed,
      '',
      '// WIRE TIME: the fingerprint IS the API. Change context and re-run —',
      '// same fingerprint → HIT → the DSL replays, no LLM call.',
      'const res = await engine.execute({',
      `  fingerprint: ${JSON.stringify(fp)},`,
      `  context: ${json(s.context ?? {})},`,
      `}${opts});`,
      '',
      '// res.meta.cache.hit === true',
    ].join('\n');
  }

  // A feature demo — show the fingerprint round-trip every read performs:
  // generate + mint once, then replay by fingerprint.
  const ctx = s.context !== undefined ? `\n  context: ${json(s.context)},` : '';
  const replayCtx = s.context !== undefined ? ', context: { /* … */ }' : '';
  return [
    "import { createQueryEngine, createPostgresAdapter } from '@niscorp/vex';",
    '',
    '// engine = createQueryEngine({ adapter, scope, generateDsl, mapToShape })',
    '',
    '// First call — intent + shape drive the DSL and the mapping. No',
    '// fingerprint given, so the engine generates it and MINTS one.',
    'const first = await engine.execute({',
    `  intent: ${JSON.stringify(s.intent)},`,
    `  shape: ${json(s.shape)},${ctx}`,
    `}${opts});`,
    'const fp = first.meta.cache.fingerprint;   // "fp_…" — the replayable identity',
    '',
    '// Every later call — replay by fingerprint, zero LLM, context varies:',
    `const res = await engine.execute({ fingerprint: fp${replayCtx} }${opts});`,
    '',
    '// res.result     → the requested shape (array | object | scalar)',
    '// res.meta.cache → { hit, fingerprint, replaced, intent }',
  ].join('\n');
};
