import type { VexScenario } from './scenarios';

// Builds the teaching snippet shown in the chrome Source tab: how a
// caller would issue this exact request against a wired engine.
export const buildSource = (s: VexScenario): string => {
  const json = (v: unknown): string => JSON.stringify(v, null, 2).replace(/\n/g, '\n  ');

  if (s.mode === 'compile') {
    return [
      "import { createQueryEngine } from '@niscorp/vex';",
      '',
      '// The analyzer runs inside compile() — before any SQL exists.',
      '// This DSL is rejected, so compile() throws VexError(invalid_dsl).',
      `const dsl = ${json(s.dsl)};`,
      '',
      'engine.compile(dsl); // ✗ cartesian product: no join between entities',
    ].join('\n');
  }

  if (s.mode === 'mutate') {
    if (s.mutation === undefined) {
      // The raw-body refusal demo: the request IS the lesson.
      return [
        '// Writes are REPLAY-ONLY. A mutation definition is not a request',
        '// shape — the wire knows { fingerprint, context } and nothing else,',
        '// so an inline definition dies at parse: 400 invalid_request.',
        '',
        `const body = ${json(s.body)};`,
        '',
        'await handleQuery({ engine, mutations: { client: db, policy } }, body, scope);',
        "// → { status: 400, body: { error: 'invalid_request', ... } }",
      ].join('\n');
    }
    return [
      "import { handleQuery, lintMutation } from '@niscorp/vex';",
      '',
      '// SEED TIME (boot, server-side): the definition is linted and stored',
      '// as a `kind: mutation` cache entry. It is never generated by an LLM',
      '// and it NEVER travels — the fingerprint is the whole API surface.',
      `const def = ${json(s.mutation)};`,
      `await engine.cache.set(${JSON.stringify(`vex-demo/${s.id}`)}, { kind: 'mutation', mutation: def, ... });`,
      '',
      '// WIRE TIME: one wire shape, reads and writes alike — the entry\'s',
      '// kind picks the pipeline. Scope comes from the session, never the body.',
      'const res = await handleQuery(',
      '  { engine, mutations: { client: db, policy } },',
      `  { fingerprint: ${JSON.stringify(`vex-demo/${s.id}`)}, context: ${json(s.context ?? {})} },`,
      `  ${json(s.scope ?? {})},`,
      ');',
      '',
      '// res.body.result → the RETURNING row(s); a refusal is a real status:',
      '// 400 scope_denied / missing_context / invalid_request.',
    ].join('\n');
  }

  const hasScope = s.scopeKey !== undefined;
  const opts = hasScope ? `, {\n  scope: ${json(s.scope ?? {})},\n}` : '';
  const ctx = s.context !== undefined ? `\n  context: ${json(s.context)},` : '';

  return [
    "import { createQueryEngine, createPostgresAdapter } from '@niscorp/vex';",
    '',
    '// engine = createQueryEngine({ adapter, scope, generateDsl, mapToShape })',
    '// First request for a shape generates + caches the DSL; later',
    '// requests with the same shape skip the LLM entirely.',
    '',
    'const res = await engine.execute({',
    `  intent: ${JSON.stringify(s.intent)},`,
    `  shape: ${json(s.shape)},${ctx}`,
    `}${opts});`,
    '',
    '// res.result        → rows in the requested shape',
    '// res.meta.cache    → { hit, key }   (shape-keyed)',
    '// res.meta.timing   → per-stage timing',
  ].join('\n');
};
